@endpoint = http://localhost:3333/api

### User取得
POST {{endpoint}}/user HTTP/1.1
Content-Type: application/json

### BloodType取得
POST {{endpoint}}/bloodtype HTTP/1.1
Content-Type: application/json

### UserProfile取得
POST {{endpoint}}/userbloodtype HTTP/1.1
Content-Type: application/json

### UserBloodType取得
POST {{endpoint}}/bloodtypeuser HTTP/1.1
Content-Type: application/json